version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    ports:
      - "27018:27017"
    networks:
      - todo-network

  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-springboot-app172.20.0.3
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=todo_db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
